apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- rbac.yaml
- frontend.yaml
- registry-secret.yaml

commonLabels:
  app.kubernetes.io/name: kubepulse
  app.kubernetes.io/part-of: kubepulse 