apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubepulse-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubepulse-role
rules:
- apiGroups: [""]
  resources: ["nodes", "pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["nodes", "pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubepulse-role-binding
subjects:
- kind: ServiceAccount
  name: kubepulse-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: kubepulse-role
  apiGroup: rbac.authorization.k8s.io 